In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
from kalshi.events import Events

events = Events()
events = events.get_all_events(all_pages=True, status='open')
events_df = pd.DataFrame(events)
display(events_df.head())

,available_on_brokers,category,collateral_return_type,event_ticker,last_updated_ts,mutually_exclusive,product_metadata,series_ticker,sub_title,title,strike_date,strike_period
0,True,World,,KXELONMARS-99,2026-02-26T08:50:31.901806Z,False,{},KXELONMARS,Before 2099,Will Elon Musk visit Mars in his lifetime?,NaN,NaN
1,True,Elections,MECNET,KXNEWPOPE-70,2026-02-26T08:50:31.901806Z,True,{},KXNEWPOPE,Before 2070,Who will the next Pope be?,NaN,NaN
2,True,Climate and Weather,,KXWARMING-50,2026-02-26T08:50:31.901806Z,False,{},KXWARMING,Before 2050,Will the world pass 2 degrees Celsius over pre...,NaN,NaN
3,True,Science and Technology,,KXMARSVRAIL-50,2026-02-26T08:50:31.901806Z,False,{},KXMARSVRAIL,Before 2050,Will a human land on Mars before California st...,NaN,NaN
4,True,Climate and Weather,,KXERUPTSUPER-0,2026-02-26T08:50:31.901806Z,False,{},KXERUPTSUPER,a supervolcano,Will a supervolcano erupt before 2050?,NaN,NaN

In [3]:
display(events_df.columns)

Index(['available_on_brokers', 'category', 'collateral_return_type',
       'event_ticker', 'last_updated_ts', 'mutually_exclusive',
       'product_metadata', 'series_ticker', 'sub_title', 'title',
       'strike_date', 'strike_period'],
      dtype='str')

In [4]:
display(events_df.describe().transpose())

                       count unique                          top  freq
available_on_brokers    5057      2                        False  2533
category                5057     15                       Sports  2384
collateral_return_type  5057      3                       MECNET  2780
event_ticker            5057   5057                KXELONMARS-99     1
last_updated_ts         5057   3888  2026-02-26T08:50:31.901806Z  1137
mutually_exclusive      5057      2                         True  2780
product_metadata        5057    504                           {}  2417
series_ticker           5057   2388                  KXHOUSERACE   358
sub_title               5057   2257                      In 2026   523
title                   5057   4944        Arizona vs New York M     3
strike_date              213     58         2026-04-07T23:00:00Z    22
strike_period             32     15                     May 2026     4

In [5]:
display(events_df['category'].value_counts())

category
Sports                    2384
Elections                 1156
Entertainment              391
Politics                   324
Economics                  310
Climate and Weather        114
Crypto                      87
Financials                  73
Companies                   69
Science and Technology      65
Mentions                    42
World                       18
Social                      16
Health                       7
Transportation               1
Name: count, dtype: int64

In [6]:
display(events_df[events_df['category'] == 'Sports'])

      available_on_brokers category collateral_return_type  \
34                    True   Sports
35                    True   Sports
54                    True   Sports
56                    True   Sports
63                    True   Sports
64                    True   Sports
237                   True   Sports                 MECNET
239                   True   Sports
249                   True   Sports
264                  False   Sports
274                   True   Sports
283                  False   Sports                 MECNET
295                  False   Sports
348                   True   Sports
349                  False   Sports
350                   True   Sports
351                   True   Sports                 MECNET
353                   True   Sports
354                   True   Sports                 MECNET
402                   True   Sports                 MECNET
419                  False   Sports                 MECNET
420                  False   Sports                 MECNET
421                  False   Sports                 MECNET
429                   True   Sports                 MECNET
430                   True   Sports                 MECNET
431                   True   Sports                 MECNET
445                   True   Sports                 MECNET
449                  False   Sports                 MECNET
450                   True   Sports                 MECNET
451                   True   Sports                 MECNET
452                   True   Sports                 MECNET
454                   True   Sports                 MECNET
457                  False   Sports                 MECNET
458                  False   Sports                 MECNET
459                  False   Sports                 MECNET
460                  False   Sports                 MECNET
461                  False   Sports                 MECNET
462                  False   Sports                 MECNET
463                   True   Sports                 MECNET
464                  False   Sports                 MECNET
465                  False   Sports                 MECNET
475                   True   Sports                 MECNET
478                   True   Sports                 MECNET
506                   True   Sports
507                   True   Sports                 MECNET
508                   True   Sports                 MECNET
509                   True   Sports                 MECNET
510                   True   Sports                 MECNET
511                   True   Sports                 MECNET
512                   True   Sports                 MECNET
513                   True   Sports                 MECNET
514                   True   Sports                 MECNET
515                   True   Sports
524                   True   Sports
1078                  True   Sports
1097                 False   Sports                 MECNET
1098                 False   Sports                 MECNET
1099                 False   Sports                 MECNET
1100                 False   Sports                 MECNET
1101                 False   Sports                 MECNET
1115                  True   Sports
1116                 False   Sports
1117                  True   Sports
1118                  True   Sports
1119                  True   Sports
1121                 False   Sports                 MECNET
1122                 False   Sports                 MECNET
1123                 False   Sports                 MECNET
1199                 False   Sports
1218                  True   Sports
1244                  True   Sports
1263                  True   Sports                 MECNET
1269                  True   Sports
1277                  True   Sports
1291                  True   Sports
1323                  True   Sports
1349                  True   Sports                 MECNET
1413                 False   Sports                 MECNET
1422                  True   Sports                 MECNET
1426                  True   Sports
1429                 False   Sports                 MECNET
1431                  True   Sports                 MECNET
1432                  True   Sports                 MECNET
1433                  True   Sports                 MECNET
1434                  True   Sports                 MECNET
1435                  True   Sports                 MECNET
1436                  True   Sports                 MECNET
1437                  True   Sports                 MECNET
1438                  True   Sports                 MECNET
1468                  True   Sports
1477                  True   Sports
1478                  True   Sports                 MECNET
1480                  True   Sports                 MECNET
1483                  True   Sports
1485                  True   Sports                 MECNET
1486                  True   Sports                 MECNET
1487                  True   Sports                 MECNET
1488                  True   Sports                 MECNET
1489                  True   Sports                 MECNET
1490                  True   Sports                 MECNET
1491                  True   Sports                 MECNET
1492                  True   Sports                 MECNET
1493                  True   Sports                 MECNET
1494                  True   Sports                 MECNET
1495                  True   Sports                 MECNET
1496                  True   Sports                 MECNET
1497                  True   Sports                 MECNET
1498                  True   Sports                 MECNET
1499                  True   Sports                 MECNET
1536                  True   Sports                 MECNET
1538                  True   Sports
1543                  True   Sports
1544                  True   Sports
1548                 False   Sports                 MECNET
1557                  True   Sports                 MECNET
1558                  True   Sports                 MECNET
1559                  True   Sports                 MECNET
1565                  True   Sports
1568                 False   Sports
1569                  True   Sports
1570                 False   Sports                 MECNET
1572                 False   Sports                 MECNET
1573                  True   Sports
1574                  True   Sports
1583                  True   Sports                 MECNET
1584                  True   Sports                 MECNET
1585                 False   Sports                 MECNET
1586                 False   Sports                 MECNET
1587                 False   Sports                 MECNET
1588                 False   Sports                 MECNET
1589                 False   Sports                 MECNET
1590                 False   Sports                 MECNET
1591                  True   Sports                 MECNET
1592                  True   Sports                 MECNET
1593                  True   Sports                 MECNET
1594                  True   Sports                 MECNET
1595                  True   Sports                 MECNET
1600                  True   Sports                 MECNET
1605                 False   Sports                 MECNET
1606                  True   Sports
1607                  True   Sports                 MECNET
1608                  True   Sports                 MECNET
1609                  True   Sports                 MECNET
1610                 False   Sports                 MECNET
1611                  True   Sports                 MECNET
1612                 False   Sports                 MECNET
1613                  True   Sports                 MECNET
1614                  True   Sports                 MECNET
1615                  True   Sports
1616                  True   Sports
1617                  True   Sports
1618                  True   Sports
1619                  True   Sports
1620                  True   Sports
1621                  True   Sports
1622                  True   Sports
1623                  True   Sports
1624                  True   Sports
1625                  True   Sports
1626                  True   Sports
1627                  True   Sports
1628                  True   Sports
1629                  True   Sports                 MECNET
1630                  True   Sports                 MECNET
1632                 False   Sports                 MECNET
1633                  True   Sports                 MECNET
1637                  True   Sports                 MECNET
1648                  True   Sports                 MECNET
1649                  True   Sports                 MECNET
1650                  True   Sports               DIRECNET
1651                  True   Sports               DIRECNET
1652                  True   Sports               DIRECNET
1653                  True   Sports               DIRECNET
1654                  True   Sports               DIRECNET
1655                  True   Sports               DIRECNET
1656                  True   Sports               DIRECNET
1657                  True   Sports               DIRECNET
1658                  True   Sports               DIRECNET
1659                  True   Sports               DIRECNET
1660                  True   Sports               DIRECNET
1661                  True   Sports               DIRECNET
1662                  True   Sports               DIRECNET
1663                  True   Sports               DIRECNET
1664                  True   Sports               DIRECNET
1665                  True   Sports               DIRECNET
1666                  True   Sports               DIRECNET
1667                  True   Sports               DIRECNET
1668                  True   Sports               DIRECNET
1669                  True   Sports               DIRECNET
1670                  True   Sports               DIRECNET
1671                  True   Sports               DIRECNET
1672                  True   Sports               DIRECNET
1673                  True   Sports               DIRECNET
1674                  True   Sports               DIRECNET
1675                  True   Sports               DIRECNET
1676                  True   Sports               DIRECNET
1677                  True   Sports               DIRECNET
1678                  True   Sports               DIRECNET
1679                  True   Sports               DIRECNET
1948                  True   Sports
1951                  True   Sports
1952                 False   Sports                 MECNET
1954                  True   Sports                 MECNET
1955                  True   Sports                 MECNET
1956                  True   Sports                 MECNET
1957                  True   Sports                 MECNET
1958                  True   Sports                 MECNET
1959                  True   Sports                 MECNET
1960                  True   Sports                 MECNET
1961                  True   Sports                 MECNET
1962                  True   Sports                 MECNET
1963                  True   Sports                 MECNET
1964                  True   Sports
1973                  True   Sports                 MECNET
1974                 False   Sports                 MECNET
1975                  True   Sports                 MECNET
1976                 False   Sports                 MECNET
1977                 False   Sports                 MECNET
1978                 False   Sports                 MECNET
1979                  True   Sports                 MECNET
1980                 False   Sports                 MECNET
1981                 False   Sports                 MECNET
1983                  True   Sports                 MECNET
1984                  True   Sports                 MECNET
1985                  True   Sports                 MECNET
1986                  True   Sports                 MECNET
1987                  True   Sports                 MECNET
1988                  True   Sports                 MECNET
1989                  True   Sports                 MECNET
1990                  True   Sports                 MECNET
1991                  True   Sports                 MECNET
1992                 False   Sports                 MECNET
1993                  True   Sports                 MECNET
1994                  True   Sports                 MECNET
1995                  True   Sports                 MECNET
1996                  True   Sports                 MECNET
1997                  True   Sports                 MECNET
2004                 False   Sports                 MECNET
2011                  True   Sports                 MECNET
2012                 False   Sports
2013                  True   Sports
2014                  True   Sports
2015                  True   Sports
2016                  True   Sports
2017                  True   Sports                 MECNET
2037                  True   Sports                 MECNET
2041                  True   Sports                 MECNET
2042                 False   Sports                 MECNET
2043                  True   Sports                 MECNET
2044                  True   Sports                 MECNET
2045                 False   Sports                 MECNET
2046                  True   Sports
2049                  True   Sports
2050                  True   Sports
2051                  True   Sports                 MECNET
2052                  True   Sports
2053                  True   Sports                 MECNET
2054                  True   Sports                 MECNET
2055                  True   Sports                 MECNET
2068                  True   Sports
2071                  True   Sports                 MECNET
2072                  True   Sports                 MECNET
2073                 False   Sports                 MECNET
2074                  True   Sports                 MECNET
2075                  True   Sports
2076                  True   Sports
2107                 False   Sports
2113                  True   Sports                 MECNET
2114                 False   Sports
2120                  True   Sports                 MECNET
2123                  True   Sports                 MECNET
2126                  True   Sports
2130                 False   Sports                 MECNET
2136                  True   Sports
2137                 False   Sports                 MECNET
2138                 False   Sports                 MECNET
2139                 False   Sports                 MECNET
2140                 False   Sports                 MECNET
2141                  True   Sports                 MECNET
2142                  True   Sports                 MECNET
2143                 False   Sports                 MECNET
2144                  True   Sports                 MECNET
2145                 False   Sports                 MECNET
2146                  True   Sports                 MECNET
2147                  True   Sports
2148                  True   Sports
2149                  True   Sports
2150                  True   Sports
2151                  True   Sports
2152                 False   Sports
2155                  True   Sports                 MECNET
2156                  True   Sports
2157                  True   Sports                 MECNET
2158                  True   Sports                 MECNET
2182                  True   Sports
2183                  True   Sports
2184                  True   Sports
2185                  True   Sports                 MECNET
2186                  True   Sports                 MECNET
2188                  True   Sports               DIRECNET
2189                  True   Sports               DIRECNET
2190                  True   Sports               DIRECNET
2191                  True   Sports               DIRECNET
2192                  True   Sports               DIRECNET
2193                  True   Sports               DIRECNET
2194                  True   Sports               DIRECNET
2195                  True   Sports               DIRECNET
2196                  True   Sports               DIRECNET
2197                  True   Sports               DIRECNET
2198                  True   Sports               DIRECNET
2199                  True   Sports               DIRECNET
2200                  True   Sports               DIRECNET
2201                  True   Sports               DIRECNET
2202                  True   Sports               DIRECNET
2203                  True   Sports               DIRECNET
2204                  True   Sports               DIRECNET
2205                  True   Sports               DIRECNET
2206                  True   Sports               DIRECNET
2207                  True   Sports               DIRECNET
2208                  True   Sports               DIRECNET
2209                  True   Sports               DIRECNET
2210                  True   Sports               DIRECNET
2211                  True   Sports               DIRECNET
2212                  True   Sports               DIRECNET
2213                  True   Sports               DIRECNET
2214                  True   Sports               DIRECNET
2215                  True   Sports               DIRECNET
2216                  True   Sports               DIRECNET
2217                  True   Sports               DIRECNET
2219                  True   Sports
2220                  True   Sports
2226                  True   Sports
2230                  True   Sports                 MECNET
2237                  True   Sports                 MECNET
2238                  True   Sports                 MECNET
2239                  True   Sports                 MECNET
2242                 False   Sports                 MECNET
2245                  True   Sports                 MECNET
2247                  True   Sports                 MECNET
2249                  True   Sports
2251                  True   Sports                 MECNET
2252                  True   Sports                 MECNET
2253                  True   Sports
2254                  True   Sports                 MECNET
2255                  True   Sports                 MECNET
2256                  True   Sports                 MECNET
2257                  True   Sports                 MECNET
2258                  True   Sports                 MECNET
2259                  True   Sports                 MECNET
2260                  True   Sports                 MECNET
2261                  True   Sports
2262                  True   Sports
2263                  True   Sports
2264                  True   Sports                 MECNET
2265                  True   Sports
2266                  True   Sports
2275                  True   Sports                 MECNET
2276                 False   Sports                 MECNET
2277                 False   Sports                 MECNET
2278                  True   Sports                 MECNET
2279                 False   Sports                 MECNET
2280                  True   Sports
2281                  True   Sports
2282                  True   Sports
2283                  True   Sports
2284                  True   Sports
2285                  True   Sports
2286                  True   Sports
2287                  True   Sports
2288                  True   Sports
2289                  True   Sports
2290                  True   Sports
2291                  True   Sports
2292                  True   Sports                 MECNET
2293                  True   Sports                 MECNET
2294                  True   Sports                 MECNET
2295                  True   Sports                 MECNET
2296                  True   Sports                 MECNET
2297                  True   Sports                 MECNET
2298                  True   Sports                 MECNET

In [3]:
from kalshi.markets import Markets
from kalshi.utils import utc_to_local
markets = Markets()
list_markets = markets.get_all_markets(all_pages=False, status='open', mve_filter='exclude')
markets_df = pd.DataFrame(list_markets)
cols = markets_df.columns
for col in cols:
    if 'time' in col:
        markets_df[col] = markets_df[col].apply(utc_to_local)

In [4]:
display(markets_df.sort_values('close_time', ascending=True).head())

,can_close_early,close_time,created_time,custom_strike,early_close_condition,event_ticker,expected_expiration_time,expiration_time,expiration_value,fractional_trading_enabled,last_price_dollars,latest_expiration_time,liquidity_dollars,market_type,no_ask_dollars,no_bid_dollars,no_sub_title,notional_value_dollars,open_interest_fp,open_time,previous_price_dollars,previous_yes_ask_dollars,previous_yes_bid_dollars,price_level_structure,price_ranges,response_price_units,result,rules_primary,rules_secondary,settlement_timer_seconds,status,strike_type,subtitle,tick_size,ticker,title,updated_time,volume_24h_fp,volume_fp,yes_ask_dollars,yes_ask_size_fp,yes_bid_dollars,yes_bid_size_fp,yes_sub_title,floor_strike,primary_participant_key
21,True,2026-03-22 21:00:00-05:00,2026-03-20 15:20:36.001376-05:00,{'baseball_team': '40866f65-2c49-4221-81af-2f6...,This market will close and expire after a winn...,KXNCAABBGAME-26MAR202200WAHTRO,2026-03-21 02:00:00-05:00,2026-03-22 21:00:00-05:00,,False,0.0000,2026-03-22 21:00:00-05:00,0.0000,binary,0.2100,0.0400,USC,1.0000,0.00,2026-03-20 15:23:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If USC wins the Washington vs USC College Base...,"Kalshi is not affiliated, associated, authoriz...",1969-12-31 18:05:00-06:00,active,structured,,1,KXNCAABBGAME-26MAR202200WAHTRO-TRO,Washington vs USC winner?,2026-03-20 15:23:00.714382-05:00,0.00,0.00,0.9600,7792.00,0.7900,400.00,USC,NaN,NaN
20,True,2026-03-22 21:00:00-05:00,2026-03-20 15:20:36.001376-05:00,{'baseball_team': '8711ba15-dd1b-4d9e-b87e-3f4...,This market will close and expire after a winn...,KXNCAABBGAME-26MAR202200WAHTRO,2026-03-21 02:00:00-05:00,2026-03-22 21:00:00-05:00,,False,0.0000,2026-03-22 21:00:00-05:00,0.0000,binary,0.8800,0.7800,Washington,1.0000,0.00,2026-03-20 15:23:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Washington wins the Washington vs USC Colle...,"Kalshi is not affiliated, associated, authoriz...",1969-12-31 18:05:00-06:00,active,structured,,1,KXNCAABBGAME-26MAR202200WAHTRO-WAH,Washington vs USC winner?,2026-03-20 15:23:00.714382-05:00,0.00,0.00,0.2200,401.00,0.1200,400.00,Washington,NaN,NaN
49,True,2026-04-03 20:00:00-05:00,2026-03-20 15:02:47.616359-05:00,{'hockey_player': 'a6deb468-1c4b-4c8f-8b40-37b...,This market will close and expire early if the...,KXNHLFIRSTGOAL-26MAR20FLACGY,2026-03-20 23:00:00-05:00,2026-04-03 20:00:00-05:00,,False,0.0000,2026-04-03 20:00:00-05:00,0.0000,binary,1.0000,1.0000,Connor Zary,1.0000,0.00,2026-03-20 15:07:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Connor Zary scores the 1st goal in the FLA ...,The following market refers to a player in the...,1969-12-31 18:04:58-06:00,active,structured,,1,KXNHLFIRSTGOAL-26MAR20FLACGY-CGYCZARY47,Connor Zary: First Goalscorer,2026-03-20 15:07:00.752404-05:00,0.00,0.00,0.0000,0.00,0.0000,0.00,Connor Zary,NaN,hockey_player
72,True,2026-04-03 20:00:00-05:00,2026-03-20 15:02:46.388457-05:00,{'hockey_player': '4fa4f42d-cdf1-475f-a301-ae6...,This market will close and expire early if the...,KXNHLPTS-26MAR20FLACGY,2026-03-20 23:00:00-05:00,2026-04-03 20:00:00-05:00,,False,0.0000,2026-04-03 20:00:00-05:00,0.0000,binary,0.6500,0.5900,Matvei Gridin: 1+,1.0000,0.00,2026-03-20 15:07:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Matvei Gridin records at least 1+ points in...,The following market refers to a player in the...,1969-12-31 18:04:59-06:00,active,structured,,1,KXNHLPTS-26MAR20FLACGY-CGYMGRIDIN92-1,Matvei Gridin: 1+ points,2026-03-20 15:07:00.752404-05:00,0.00,0.00,0.4100,33.00,0.3500,400.00,Matvei Gridin: 1+,0.5,hockey_player
71,True,2026-04-03 20:00:00-05:00,2026-03-20 15:02:46.388457-05:00,{'hockey_player': '4fa4f42d-cdf1-475f-a301-ae6...,This market will close and expire early if the...,KXNHLPTS-26MAR20FLACGY,2026-03-20 23:00:00-05:00,2026-04-03 20:00:00-05:00,,False,0.0000,2026-04-03 20:00:00-05:00,0.0000,binary,1.0000,1.0000,Matvei Gridin: 2+,1.0000,0.00,2026-03-20 15:07:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Matvei Gridin records at least 2+ points in...,The following market refers to a player in the...,1969-12-31 18:04:59-06:00,active,structured,,1,KXNHLPTS-26MAR20FLACGY-CGYMGRIDIN92-2,Matvei Gridin: 2+ points,2026-03-20 15:07:00.752404-05:00,0.00,0.00,0.0000,0.00,0.0000,0.00,Matvei Gridin: 2+,1.5,hockey_player

In [12]:
display(markets_df)

,can_close_early,close_time,created_time,custom_strike,early_close_condition,event_ticker,expected_expiration_time,expiration_time,expiration_value,fractional_trading_enabled,last_price_dollars,latest_expiration_time,liquidity_dollars,market_type,no_ask_dollars,no_bid_dollars,no_sub_title,notional_value_dollars,open_interest_fp,open_time,previous_price_dollars,previous_yes_ask_dollars,previous_yes_bid_dollars,price_level_structure,price_ranges,response_price_units,result,rules_primary,rules_secondary,settlement_timer_seconds,status,strike_type,subtitle,tick_size,ticker,title,updated_time,volume_24h_fp,volume_fp,yes_ask_dollars,yes_ask_size_fp,yes_bid_dollars,yes_bid_size_fp,yes_sub_title,floor_strike,primary_participant_key
0,True,2026-04-04 13:30:00-05:00,2026-03-20 15:41:00.858689-05:00,{'esports_competitor': '039ed30e-a367-4eca-be1...,This market will close and expire after a winn...,KXVALORANTMAP-26MAR21GNGMDR-2,2026-03-21 17:30:00-05:00,2026-04-04 13:30:00-05:00,,False,0.0000,2026-04-04 13:30:00-05:00,0.0000,binary,0.9900,0.0100,Mandatory,1.0000,0.00,2026-03-20 15:55:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Mandatory wins map 2 in the VCL EMEA: 2026:...,,1969-12-31 18:01:59-06:00,active,structured,,1,KXVALORANTMAP-26MAR21GNGMDR-2-MDR,Will Mandatory win map 2 in the GnG Amazigh vs...,2026-03-20 15:55:00.714690-05:00,0.00,0.00,0.9900,661.00,0.0100,661.00,Mandatory,NaN,NaN
1,True,2026-04-04 13:30:00-05:00,2026-03-20 15:41:00.858689-05:00,{'esports_competitor': 'b069d015-6cae-4e71-b68...,This market will close and expire after a winn...,KXVALORANTMAP-26MAR21GNGMDR-2,2026-03-21 17:30:00-05:00,2026-04-04 13:30:00-05:00,,False,0.0000,2026-04-04 13:30:00-05:00,0.0000,binary,0.9900,0.0100,GnG Amazigh,1.0000,0.00,2026-03-20 15:55:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If GnG Amazigh wins map 2 in the VCL EMEA: 202...,,1969-12-31 18:01:59-06:00,active,structured,,1,KXVALORANTMAP-26MAR21GNGMDR-2-GNG,Will GnG Amazigh win map 2 in the GnG Amazigh ...,2026-03-20 15:55:00.714690-05:00,0.00,0.00,0.9900,661.00,0.0100,661.00,GnG Amazigh,NaN,NaN
2,True,2026-04-04 13:30:00-05:00,2026-03-20 15:41:00.307873-05:00,{'esports_competitor': '039ed30e-a367-4eca-be1...,This market will close and expire after a winn...,KXVALORANTMAP-26MAR21GNGMDR-1,2026-03-21 17:30:00-05:00,2026-04-04 13:30:00-05:00,,False,0.0000,2026-04-04 13:30:00-05:00,0.0000,binary,0.9900,0.0100,Mandatory,1.0000,0.00,2026-03-20 15:55:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Mandatory wins map 1 in the VCL EMEA: 2026:...,,1969-12-31 18:01:59-06:00,active,structured,,1,KXVALORANTMAP-26MAR21GNGMDR-1-MDR,Will Mandatory win map 1 in the GnG Amazigh vs...,2026-03-20 15:55:00.714690-05:00,0.00,0.00,0.9900,661.00,0.0100,661.00,Mandatory,NaN,NaN
3,True,2026-04-04 13:30:00-05:00,2026-03-20 15:41:00.307873-05:00,{'esports_competitor': 'b069d015-6cae-4e71-b68...,This market will close and expire after a winn...,KXVALORANTMAP-26MAR21GNGMDR-1,2026-03-21 17:30:00-05:00,2026-04-04 13:30:00-05:00,,False,0.0000,2026-04-04 13:30:00-05:00,0.0000,binary,0.9900,0.0100,GnG Amazigh,1.0000,0.00,2026-03-20 15:55:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If GnG Amazigh wins map 1 in the VCL EMEA: 202...,,1969-12-31 18:01:59-06:00,active,structured,,1,KXVALORANTMAP-26MAR21GNGMDR-1-GNG,Will GnG Amazigh win map 1 in the GnG Amazigh ...,2026-03-20 15:55:00.714690-05:00,0.00,0.00,0.9900,661.00,0.0100,661.00,GnG Amazigh,NaN,NaN
4,True,2026-04-04 13:30:00-05:00,2026-03-20 15:32:10.972756-05:00,{'esports_competitor': '039ed30e-a367-4eca-be1...,This market will close and expire after a winn...,KXVALORANTGAME-26MAR21GNGMDR,2026-03-21 17:30:00-05:00,2026-04-04 13:30:00-05:00,,False,0.0000,2026-04-04 13:30:00-05:00,0.0000,binary,0.9300,0.1600,Mandatory,1.0000,0.00,2026-03-20 15:37:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Mandatory wins the VCL EMEA: 2026: GnG Amaz...,,1969-12-31 18:01:58-06:00,active,structured,,1,KXVALORANTGAME-26MAR21GNGMDR-MDR,Will Mandatory win the GnG Amazigh vs. Mandato...,2026-03-20 15:37:00.714168-05:00,0.00,0.00,0.8400,20.00,0.0700,10.00,Mandatory,NaN,NaN
5,True,2026-04-04 13:30:00-05:00,2026-03-20 15:32:10.972756-05:00,{'esports_competitor': 'b069d015-6cae-4e71-b68...,This market will close and expire after a winn...,KXVALORANTGAME-26MAR21GNGMDR,2026-03-21 17:30:00-05:00,2026-04-04 13:30:00-05:00,,False,0.0000,2026-04-04 13:30:00-05:00,0.0000,binary,0.9300,0.1600,GnG Amazigh,1.0000,0.00,2026-03-20 15:37:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If GnG Amazigh wins the VCL EMEA: 2026: GnG Am...,,1969-12-31 18:01:58-06:00,active,structured,,1,KXVALORANTGAME-26MAR21GNGMDR-GNG,Will GnG Amazigh win the GnG Amazigh vs. Manda...,2026-03-20 15:37:00.714168-05:00,0.00,0.00,0.8400,20.00,0.0700,10.00,GnG Amazigh,NaN,NaN
6,True,2026-04-04 13:00:00-05:00,2026-03-20 15:31:01.186189-05:00,{'esports_competitor': 'e7b6d585-4698-46e9-b43...,This market will close and expire after a winn...,KXLOLMAP-26MAR21JDGBLG-3,2026-03-21 17:00:00-05:00,2026-04-04 13:00:00-05:00,,False,0.0000,2026-04-04 13:00:00-05:00,0.0000,binary,0.7300,0.6500,JD Gaming,1.0000,0.00,2026-03-20 15:45:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If JD Gaming wins map 3 in the First Stand 202...,,1969-12-31 18:01:59-06:00,active,structured,,1,KXLOLMAP-26MAR21JDGBLG-3-JDG,Will JD Gaming win map 3 in the JD Gaming vs. ...,2026-03-20 15:45:00.714189-05:00,0.00,0.00,0.3500,500.00,0.2700,750.00,JD Gaming,NaN,NaN
7,True,2026-04-04 13:00:00-05:00,2026-03-20 15:31:01.186189-05:00,{'esports_competitor': '1942e522-e098-4311-8f0...,This market will close and expire after a winn...,KXLOLMAP-26MAR21JDGBLG-3,2026-03-21 17:00:00-05:00,2026-04-04 13:00:00-05:00,,False,0.0000,2026-04-04 13:00:00-05:00,0.0000,binary,0.3500,0.2200,Bilibili Gaming,1.0000,0.00,2026-03-20 15:45:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Bilibili Gaming wins map 3 in the First Sta...,,1969-12-31 18:01:59-06:00,active,structured,,1,KXLOLMAP-26MAR21JDGBLG-3-BLG,Will Bilibili Gaming win map 3 in the JD Gamin...,2026-03-20 15:45:00.714189-05:00,0.00,0.00,0.7800,500.00,0.6500,500.00,Bilibili Gaming,NaN,NaN
8,True,2026-04-04 13:00:00-05:00,2026-03-20 15:31:00.568453-05:00,{'esports_competitor': 'e7b6d585-4698-46e9-b43...,This market will close and expire after a winn...,KXLOLMAP-26MAR21JDGBLG-2,2026-03-21 17:00:00-05:00,2026-04-04 13:00:00-05:00,,False,0.0000,2026-04-04 13:00:00-05:00,0.0000,binary,0.7300,0.6500,JD Gaming,1.0000,0.00,2026-03-20 15:45:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If JD Gaming wins map 2 in the First Stand 202...,,1969-12-31 18:01:59-06:00,active,structured,,1,KXLOLMAP-26MAR21JDGBLG-2-JDG,Will JD Gaming win map 2 in the JD Gaming vs. ...,2026-03-20 15:45:00.714189-05:00,0.00,0.00,0.3500,500.00,0.2700,750.00,JD Gaming,NaN,NaN
9,True,2026-04-04 13:00:00-05:00,2026-03-20 15:31:00.568453-05:00,{'esports_competitor': '1942e522-e098-4311-8f0...,This market will close and expire after a winn...,KXLOLMAP-26MAR21JDGBLG-2,2026-03-21 17:00:00-05:00,2026-04-04 13:00:00-05:00,,False,0.0000,2026-04-04 13:00:00-05:00,0.0000,binary,0.3500,0.2200,Bilibili Gaming,1.0000,0.00,2026-03-20 15:45:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Bilibili Gaming wins map 2 in the First Sta...,,1969-12-31 18:01:59-06:00,active,structured,,1,KXLOLMAP-26MAR21JDGBLG-2-BLG,Will Bilibili Gaming win map 2 in the JD Gamin...,2026-03-20 15:45:00.714189-05:00,0.00,0.00,0.7800,500.00,0.6500,500.00,Bilibili Gaming,NaN,NaN
10,True,2026-04-04 13:00:00-05:00,2026-03-20 15:30:59.967323-05:00,{'esports_competitor': 'e7b6d585-4698-46e9-b43...,This market will close and expire after a winn...,KXLOLMAP-26MAR21JDGBLG-1,2026-03-21 17:00:00-05:00,2026-04-04 13:00:00-05:00,,False,0.0000,2026-04-04 13:00:00-05:00,0.0000,binary,0.7300,0.6500,JD Gaming,1.0000,0.00,2026-03-20 15:45:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If JD Gaming wins map 1 in the First Stand 202...,,1969-12-31 18:01:59-06:00,active,structured,,1,KXLOLMAP-26MAR21JDGBLG-1-JDG,Will JD Gaming win map 1 in the JD Gaming vs. ...,2026-03-20 15:45:00.714189-05:00,0.00,0.00,0.3500,500.00,0.2700,750.00,JD Gaming,NaN,NaN
11,True,2026-04-04 13:00:00-05:00,2026-03-20 15:30:59.967323-05:00,{'esports_competitor': '1942e522-e098-4311-8f0...,This market will close and expire after a winn...,KXLOLMAP-26MAR21JDGBLG-1,2026-03-21 17:00:00-05:00,2026-04-04 13:00:00-05:00,,False,0.0000,2026-04-04 13:00:00-05:00,0.0000,binary,0.3500,0.2200,Bilibili Gaming,1.0000,0.00,2026-03-20 15:45:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Bilibili Gaming wins map 1 in the First Sta...,,1969-12-31 18:01:59-06:00,active,structured,,1,KXLOLMAP-26MAR21JDGBLG-1-BLG,Will Bilibili Gaming win map 1 in the JD Gamin...,2026-03-20 15:45:00.714189-05:00,0.00,0.00,0.7800,500.00,0.6500,500.00,Bilibili Gaming,NaN,NaN
12,True,2026-04-04 13:00:00-05:00,2026-03-20 15:30:52.133905-05:00,NaN,This market will close and expire after the ev...,KXLOLTOTALMAPS-26MAR21JDGBLG,2026-03-21 17:00:00-05:00,2026-04-04 13:00:00-05:00,,False,0.0000,2026-04-04 13:00:00-05:00,0.0000,binary,0.7600,0.6800,Over 4.5 maps,1.0000,0.00,2026-03-20 15:35:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If over 4.5 maps are played in the First Stand...,,1969-12-31 18:01:59-06:00,active,greater,,1,KXLOLTOTALMAPS-26MAR21JDGBLG-5,Will over 4.5 maps be played in the JD Gaming ...,2026-03-20 15:35:00.714556-05:00,0.00,0.00,0.3200,500.00,0.2400,500.00,Over 4.5 maps,4.5,NaN
13,True,2026-04-04 13:00:00-05:00,2026-03-20 15:30:52.133905-05:00,NaN,This market will close and expire after the ev...,KXLOLTOTALMAPS-26MAR21JDGBLG,2026-03-21 17:00:00-05:00,2026-04-04 13:00:00-05:00,,False,0.0000,2026-04-04 13:00:00-05:00,0.0000,binary,0.4300,0.3500,Over 3.5 maps,1.0000,0.00,2026-03-20 15:35:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If over 3.5 maps are played in the First Stand...,,1969-12-31 18:01:59-06:00,active,greater,,1,KXLOLTOTALMAPS-26MAR21JDGBLG-4,Will over 3.5 maps be played in the JD Gaming ...,2026-03-20 15:35:00.714556-05:00,0.00,0.00,0.6500,500.00,0.5700,507.00,Over 3.5 maps,3.5,NaN
14,True,2026-04-04 09:00:00-05:00,2026-03-20 15:24:02.776794-05:00,{'tennis_competitor': 'af6bf52a-0c5a-48c9-9deb...,This market will close and expire after a winn...,KXWTAMATCH-26MAR21SHNBEN,2026-03-21 12:00:00-05:00,2026-04-04 09:00:00-05:00,,False,0.0000,2026-04-04 09:00:00-05:00,0.0000,binary,0.9100,0.2100,Diana Shnaider,1.0000,0.00,2026-03-20 15:27:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Diana Shnaider wins the Shnaider vs Bencic ...,The following market refers to the Shnaider vs...,1969-12-31 18:01:00-06:00,active,structured,,1,KXWTAMATCH-26MAR21SHNBEN-SHN,Will Diana Shnaider win the Shnaider vs Bencic...,2026-03-20 15:27:00.714587-05:00,0.00,0.00,0.7900,10.00,0.0900,10.00,Diana Shnaider,NaN,NaN
15,True,2026-04-04 09:00:00-05:00,2026-03-20 15:24:02.776794-05:00,{'tennis_competitor': '694b63b8-6c41-4148-a4f8...,This market will close and expire after a winn...,KXWTAMATCH-26MAR21SHNBEN,2026-03-21 12:00:00-05:00,2026-04-04 09:00:00-05:00,,False,0.0000,2026-04-04 09:00:00-05:00,0.0000,binary,0.9100,0.2100,Belinda Bencic,1.0000,0.00,2026-03-20 15:27:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Belinda Bencic wins the Shnaider vs Bencic ...,The following market refers to the Shnaider vs...,1969-12-31 18:01:00-06:00,active,structured,,1,KXWTAMATCH-26MAR21SHNBEN-BEN,Will Belinda Bencic win the Shnaider vs Bencic...,2026-03-20 15:27:00.714587-05:00,0.00,0.00,0.7900,10.00,0.0900,10.00,Belinda Bencic,NaN,NaN
16,True,2026-04-04 09:00:00-05:00,2026-03-20 15:24:02.419506-05:00,{'tennis_competitor': '8205fc30-c34f-4359-a99e...,This market will close and expire after a winn...,KXWTAMATCH-26MAR21ZAKMBO,2026-03-21 12:00:00-05:00,2026-04-04 09:00:00-05:00,,False,0.0000,2026-04-04 09:00:00-05:00,0.0000,binary,0.9100,0.2100,Anastasia Zakharova,1.0000,0.00,2026-03-20 15:27:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Anastasia Zakharova wins the Zakharova vs M...,The following market refers to the Zakharova v...,1969-12-31 18:01:00-06:00,active,structured,,1,KXWTAMATCH-26MAR21ZAKMBO-ZAK,Will Anastasia Zakharova win the Zakharova vs ...,2026-03-20 15:27:00.714587-05:00,0.00,0.00,0.7900,10.00,0.0900,10.00,Anastasia Zakharova,NaN,NaN
17,True,2026-04-04 09:00:00-05:00,2026-03-20 15:24:02.419506-05:00,{'tennis_competitor': '614cf010-1491-4c35-a153...,This market will close and expire after a winn...,KXWTAMATCH-26MAR21ZAKMBO,2026-03-21 12:00:00-05:00,2026-04-04 09:00:00-05:00,,False,0.0000,2026-04-04 09:00:00-05:00,0.0000,binary,0.9100,0.2100,Victoria Mboko,1.0000,0.00,2026-03-20 15:27:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Victoria Mboko wins the Zakharova vs Mboko ...,The following market refers to the Zakharova v...,1969-12-31 18:01:00-06:00,active,structured,,1,KXWTAMATCH-26MAR21ZAKMBO-MBO,Will Victoria Mboko win the Zakharova vs Mboko...,2026-03-20 15:27:00.714587-05:00,0.00,0.00,0.7900,10.00,0.0900,10.00,Victoria Mboko,NaN,NaN
18,True,2026-04-04 13:00:00-05:00,2026-03-20 15:21:17.862151-05:00,{'esports_competitor': 'e7b6d585-4698-46e9-b43...,This market will close and expire after a winn...,KXLOLGAME-26MAR21JDGBLG,2026-03-21 17:00:00-05:00,2026-04-04 13:00:00-05:00,,False,0.0000,2026-04-04 13:00:00-05:00,0.0000,binary,0.8400,0.8100,JD Gaming,1.0000,0.00,2026-03-20 15:25:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If JD Gaming wins the First Stand 2026: JD Gam...,,1969-12-31 18:01:59-06:00,active,structured,,1,KXLOLGAME-26MAR21JDGBLG-JDG,Will JD Gaming win the JD Gaming vs. Bilibili ...,2026-03-20 15:25:00.715005-05:00,0.00,0.00,0.1900,2000.00,0.1600,500.00,JD Gaming,NaN,NaN
19,True,2026-04-04 13:00:00-05:00,2026-03-20 15:21:17.862151-05:00,{'esports_competitor': '1942e522-e098-4311-8f0...,This market will close and expire after a winn...,KXLOLGAME-26MAR21JDGBLG,2026-03-21 17:00:00-05:00,2026-04-04 13:00:00-05:00,,False,0.7900,2026-04-04 13:00:00-05:00,0.0000,binary,0.2300,0.2100,Bilibili Gaming,1.0000,26.00,2026-03-20 15:25:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Bilibili Gaming wins the First Stand 2026: ...,,1969-12-31 18:01:59-06:00,active,structured,,1,KXLOLGAME-26MAR21JDGBLG-BLG,Will Bilibili Gaming win the JD Gaming vs. Bil...,2026-03-20 15:25:00.715005-05:00,26.00,26.00,0.7900,4.00,0.7700,500.00,Bilibili Gaming,NaN,NaN
20,True,2026-03-22 21:00:00-05:00,2026-03-20 15:20:36.001376-05:00,{'baseball_team': '8711ba15-dd1b-4d9e-b87e-3f4...,This market will close and expire after a winn...,KXNCAABBGAME-26MAR202200WAHTRO,2026-03-21 02:00:00-05:00,2026-03-22 21:00:00-05:00,,False,0.0000,2026-03-22 21:00:00-05:00,0.0000,binary,0.8800,0.7800,Washington,1.0000,0.00,2026-03-20 15:23:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Washington wins the Washington vs USC Colle...,"Kalshi is not affiliated, associated, authoriz...",1969-12-31 18:05:00-06:00,active,structured,,1,KXNCAABBGAME-26MAR202200WAHTRO-WAH,Washington vs USC winner?,2026-03-20 15:23:00.714382-05:00,0.00,0.00,0.2200,401.00,0.1200,400.00,Washington,NaN,NaN
21,True,2026-03-22 21:00:00-05:00,2026-03-20 15:20:36.001376-05:00,{'baseball_team': '40866f65-2c49-4221-81af-2f6...,This market will close and expire after a winn...,KXNCAABBGAME-26MAR202200WAHTRO,2026-03-21 02:00:00-05:00,2026-03-22 21:00:00-05:00,,False,0.0000,2026-03-22 21:00:00-05:00,0.0000,binary,0.2100,0.0400,USC,1.0000,0.00,2026-03-20 15:23:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If USC wins the Washington vs USC College Base...,"Kalshi is not affiliated, associated, authoriz...",1969-12-31 18:05:00-06:00,active,structured,,1,KXNCAABBGAME-26MAR202200WAHTRO-TRO,Washington vs USC winner?,2026-03-20 15:23:00.714382-05:00,0.00,0.00,0.9600,7792.00,0.7900,400.00,USC,NaN,NaN
22,True,2026-04-03 20:00:00-05:00,2026-03-20 15:02:47.616359-05:00,{'hockey_player': '5fe03ab6-d9cd-41b8-a108-9ab...,This market will close and expire early if the...,KXNHLFIRSTGOAL-26MAR20FLACGY,2026-03-20 23:00:00-05:00,2026-04-03 20:00:00-05:00,,False,0.0000,2026-04-03 20:00:00-05:00,0.0000,binary,1.0000,0.0000,Tomas Nosek,1.0000,0.00,2026-03-20 15:07:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Tomas Nosek scores the 1st goal in the FLA ...,The following market refers to a player in the...,1969-12-31 18:04:58-06:00,active,structured,,1,KXNHLFIRSTGOAL-26MAR20FLACGY-FLATNOSEK92,Tomas Nosek: First Goalscorer,2026-03-20 15:07:00.752404-05:00,0.00,0.00,1.0000,0.00,0.0000,0.00,Tomas Nosek,NaN,hockey_player
23,True,2026-04-03 20:00:00-05:00,2026-03-20 15:02:47.616359-05:00,{'hockey_player': '14e76c50-6c29-4da3-ace8-6ab...,This market will close and expire early if the...,KXNHLFIRSTGOAL-26MAR20FLACGY,2026-03-20 23:00:00-05:00,2026-04-03 20:00:00-05:00,,False,0.0000,2026-04-03 20:00:00-05:00,0.0000,binary,1.0000,1.0000,Seth Jones,1.0000,0.00,2026-03-20 15:07:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Seth Jones scores the 1st goal in the FLA P...,The following market refers to a player in the...,1969-12-31 18:04:58-06:00,active,structured,,1,KXNHLFIRSTGOAL-26MAR20FLACGY-FLASJONES3,Seth Jones: First Goalscorer,2026-03-20 15:07:00.752404-05:00,0.00,0.00,0.0000,0.00,0.0000,0.00,Seth Jones,NaN,hockey_player
24,True,2026-04-03 20:00:00-05:00,2026-03-20 15:02:47.616359-05:00,{'hockey_player': '713436d4-b2ec-4af5-907b-9f9...,This market will close and expire early if the...,KXNHLFIRSTGOAL-26MAR20FLACGY,2026-03-20 23:00:00-05:00,2026-04-03 20:00:00-05:00,,False,0.0000,2026-04-03 20:00:00-05:00,0.0000,binary,1.0000,1.0000,Sam Bennett,1.0000,0.00,2026-03-20 15:07:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Sam Bennett scores the 1st goal in the FLA ...,The following market refers to a player in the...,1969-12-31 18:04:58-06:00,active,structured,,1,KXNHLFIRSTGOAL-26MAR20FLACGY-FLASBENNETT9,Sam Bennett: First Goalscorer,2026-03-20 15:07:00.752404-05:00,0.00,0.00,0.0000,0.00,0.0000,0.00,Sam Bennett,NaN,hockey_player

In [6]:
display(markets_df.describe().transpose())

              count  mean       std  min  25%  50%  75%  max
tick_size     100.0  1.00  0.000000  1.0  1.0  1.0  1.0  1.0
floor_strike   50.0  1.48  0.936559  0.5  0.5  1.5  2.5  4.5

In [7]:
display(markets_df.describe().transpose())

              count  mean       std  min  25%  50%  75%  max
tick_size     100.0  1.00  0.000000  1.0  1.0  1.0  1.0  1.0
floor_strike   50.0  1.48  0.936559  0.5  0.5  1.5  2.5  4.5

In [8]:
orderbook = markets.get_market_orderbook('KXNCAABBGAME-26MAR202130LBSCBR-CBR')

In [9]:
display(orderbook)

{'orderbook_fp': {'no_dollars': [['0.0100', '1461.00'],
   ['0.0200', '150.00'],
   ['0.0300', '25.00']],
  'yes_dollars': [['0.0100', '1561.00'],
   ['0.0200', '200.00'],
   ['0.0300', '50.00']]}}

In [10]:
market_trades = markets.get_market_trades('KXNCAABBGAME-26MAR202130LBSCBR-CBR')

In [11]:
display(market_trades)

[]