In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
from kalshi.events import Events

events = Events()
events = events.get_all_events(all_pages=True, status='open')
events_df = pd.DataFrame(events)
display(events_df.head())

,available_on_brokers,category,collateral_return_type,event_ticker,last_updated_ts,mutually_exclusive,series_ticker,strike_period,sub_title,title,product_metadata,strike_date
0,True,World,,KXELONMARS-99,2026-02-26T08:50:31.901806Z,False,KXELONMARS,,Before 2099,Will Elon Musk visit Mars in his lifetime?,NaN,NaN
1,True,World,MECNET,KXNEWPOPE-70,2026-02-26T08:50:31.901806Z,True,KXNEWPOPE,,Before 2070,Who will the next Pope be?,NaN,NaN
2,True,Climate and Weather,,KXWARMING-50,2026-02-26T08:50:31.901806Z,False,KXWARMING,,Before 2050,Will the world pass 2 degrees Celsius over pre...,NaN,NaN
3,True,Science and Technology,,KXMARSVRAIL-50,2026-02-26T08:50:31.901806Z,False,KXMARSVRAIL,,Before 2050,Will a human land on Mars before California st...,NaN,NaN
4,True,Climate and Weather,,KXERUPTSUPER-0,2026-02-26T08:50:31.901806Z,False,KXERUPTSUPER,,a supervolcano,Will a supervolcano erupt before 2050?,NaN,NaN

In [3]:
display(events_df.columns)

Index(['available_on_brokers', 'category', 'collateral_return_type',
       'event_ticker', 'last_updated_ts', 'mutually_exclusive',
       'series_ticker', 'strike_period', 'sub_title', 'title',
       'product_metadata', 'strike_date'],
      dtype='str')

In [4]:
display(events_df.describe().transpose())

,count,unique,top,freq
available_on_brokers,4703,2,False,2380
category,4703,15,Sports,2411
collateral_return_type,4703,3,MECNET,2855
event_ticker,4703,4703,KXELONMARS-99,1
last_updated_ts,4703,2745,2026-02-26T08:50:31.901806Z,1911
mutually_exclusive,4703,2,True,2855
series_ticker,4703,2194,KXHOUSERACE,358
strike_period,4703,18,,4669
sub_title,4703,2478,In 2026,518
title,4703,4680,Who will the next Pope be?,2
product_metadata,2448,327,"{'competition': 'FIFA World Cup', 'competition...",54
strike_date,134,49,2026-03-20T14:00:00Z,14

In [5]:
display(events_df['category'].value_counts())

category
Sports                    2411
Politics                   734
Elections                  643
Entertainment              282
Economics                  267
Climate and Weather         71
Science and Technology      63
Companies                   61
Crypto                      60
Financials                  40
Mentions                    24
World                       22
Social                      19
Health                       5
Transportation               1
Name: count, dtype: int64

In [6]:
display(events_df[events_df['category'] == 'Sports'])

      available_on_brokers category collateral_return_type  \
35                    True   Sports
54                   False   Sports
56                    True   Sports
63                    True   Sports
64                    True   Sports
236                  False   Sports                 MECNET
238                   True   Sports
248                   True   Sports
262                  False   Sports
272                   True   Sports
279                  False   Sports                 MECNET
288                  False   Sports
331                   True   Sports
332                  False   Sports
333                   True   Sports
334                   True   Sports                 MECNET
336                   True   Sports
337                   True   Sports                 MECNET
404                   True   Sports                 MECNET
406                   True   Sports                 MECNET
407                   True   Sports                 MECNET
423                   True   Sports                 MECNET
425                  False   Sports                 MECNET
426                  False   Sports                 MECNET
427                   True   Sports                 MECNET
428                   True   Sports                 MECNET
431                   True   Sports                 MECNET
442                   True   Sports                 MECNET
445                   True   Sports                 MECNET
472                   True   Sports
473                   True   Sports                 MECNET
474                   True   Sports                 MECNET
475                   True   Sports                 MECNET
476                   True   Sports                 MECNET
477                   True   Sports                 MECNET
478                   True   Sports                 MECNET
479                   True   Sports                 MECNET
480                   True   Sports                 MECNET
481                   True   Sports
490                   True   Sports
1038                  True   Sports
1057                 False   Sports                 MECNET
1058                 False   Sports                 MECNET
1059                 False   Sports                 MECNET
1060                 False   Sports                 MECNET
1061                 False   Sports                 MECNET
1075                  True   Sports
1076                 False   Sports
1077                  True   Sports
1078                  True   Sports
1079                  True   Sports
1082                 False   Sports                 MECNET
1083                 False   Sports                 MECNET
1084                 False   Sports                 MECNET
1157                 False   Sports
1175                  True   Sports
1202                 False   Sports
1219                  True   Sports                 MECNET
1225                  True   Sports
1232                  True   Sports
1247                  True   Sports
1278                  True   Sports
1305                  True   Sports                 MECNET
1368                 False   Sports                 MECNET
1376                  True   Sports                 MECNET
1380                  True   Sports
1382                 False   Sports                 MECNET
1384                  True   Sports                 MECNET
1385                  True   Sports                 MECNET
1386                  True   Sports                 MECNET
1387                  True   Sports                 MECNET
1388                  True   Sports                 MECNET
1389                  True   Sports                 MECNET
1390                  True   Sports                 MECNET
1391                  True   Sports                 MECNET
1393                 False   Sports
1423                  True   Sports
1432                  True   Sports
1433                  True   Sports                 MECNET
1435                  True   Sports                 MECNET
1438                  True   Sports
1440                  True   Sports                 MECNET
1441                  True   Sports                 MECNET
1442                  True   Sports                 MECNET
1443                  True   Sports                 MECNET
1444                  True   Sports                 MECNET
1445                  True   Sports                 MECNET
1446                  True   Sports                 MECNET
1447                  True   Sports                 MECNET
1448                  True   Sports                 MECNET
1449                  True   Sports                 MECNET
1450                  True   Sports                 MECNET
1451                  True   Sports                 MECNET
1452                  True   Sports                 MECNET
1453                  True   Sports                 MECNET
1454                  True   Sports                 MECNET
1491                  True   Sports                 MECNET
1493                  True   Sports
1498                  True   Sports
1499                  True   Sports
1503                 False   Sports                 MECNET
1512                  True   Sports                 MECNET
1513                  True   Sports                 MECNET
1514                  True   Sports                 MECNET
1518                  True   Sports
1521                 False   Sports
1522                  True   Sports
1523                 False   Sports                 MECNET
1525                 False   Sports                 MECNET
1526                  True   Sports
1527                  True   Sports
1536                  True   Sports                 MECNET
1537                  True   Sports                 MECNET
1538                 False   Sports                 MECNET
1539                 False   Sports                 MECNET
1540                 False   Sports                 MECNET
1541                 False   Sports                 MECNET
1542                 False   Sports                 MECNET
1543                 False   Sports                 MECNET
1544                  True   Sports                 MECNET
1545                 False   Sports                 MECNET
1546                  True   Sports                 MECNET
1547                  True   Sports                 MECNET
1548                  True   Sports                 MECNET
1553                  True   Sports                 MECNET
1555                 False   Sports                 MECNET
1556                  True   Sports
1557                  True   Sports                 MECNET
1558                  True   Sports                 MECNET
1559                  True   Sports                 MECNET
1560                 False   Sports                 MECNET
1561                  True   Sports                 MECNET
1562                  True   Sports                 MECNET
1563                  True   Sports                 MECNET
1564                 False   Sports
1565                  True   Sports
1566                  True   Sports
1567                 False   Sports
1568                 False   Sports
1569                  True   Sports
1570                  True   Sports
1571                  True   Sports
1572                  True   Sports
1573                  True   Sports
1574                  True   Sports
1575                  True   Sports
1576                  True   Sports
1578                 False   Sports                 MECNET
1579                  True   Sports                 MECNET
1593                  True   Sports                 MECNET
1594                  True   Sports                 MECNET
1595                  True   Sports               DIRECNET
1596                  True   Sports               DIRECNET
1597                  True   Sports               DIRECNET
1598                  True   Sports               DIRECNET
1599                  True   Sports               DIRECNET
1600                  True   Sports               DIRECNET
1601                  True   Sports               DIRECNET
1602                  True   Sports               DIRECNET
1603                  True   Sports               DIRECNET
1604                  True   Sports               DIRECNET
1605                  True   Sports               DIRECNET
1606                  True   Sports               DIRECNET
1607                  True   Sports               DIRECNET
1608                  True   Sports               DIRECNET
1609                  True   Sports               DIRECNET
1610                  True   Sports               DIRECNET
1611                  True   Sports               DIRECNET
1612                  True   Sports               DIRECNET
1613                  True   Sports               DIRECNET
1614                  True   Sports               DIRECNET
1615                  True   Sports               DIRECNET
1616                  True   Sports               DIRECNET
1617                  True   Sports               DIRECNET
1618                  True   Sports               DIRECNET
1619                  True   Sports               DIRECNET
1620                  True   Sports               DIRECNET
1621                  True   Sports               DIRECNET
1622                  True   Sports               DIRECNET
1623                  True   Sports               DIRECNET
1624                  True   Sports               DIRECNET
1800                  True   Sports
1803                  True   Sports
1804                 False   Sports                 MECNET
1806                 False   Sports                 MECNET
1807                  True   Sports                 MECNET
1808                  True   Sports                 MECNET
1809                  True   Sports                 MECNET
1810                  True   Sports                 MECNET
1811                  True   Sports                 MECNET
1812                  True   Sports                 MECNET
1813                  True   Sports                 MECNET
1814                  True   Sports                 MECNET
1815                  True   Sports                 MECNET
1816                  True   Sports
1825                  True   Sports                 MECNET
1826                 False   Sports                 MECNET
1827                 False   Sports                 MECNET
1828                 False   Sports                 MECNET
1829                 False   Sports                 MECNET
1830                 False   Sports                 MECNET
1831                 False   Sports                 MECNET
1833                  True   Sports                 MECNET
1834                  True   Sports                 MECNET
1835                  True   Sports                 MECNET
1836                  True   Sports                 MECNET
1837                  True   Sports                 MECNET
1838                  True   Sports                 MECNET
1839                  True   Sports                 MECNET
1840                  True   Sports                 MECNET
1841                  True   Sports                 MECNET
1842                  True   Sports                 MECNET
1843                  True   Sports                 MECNET
1844                  True   Sports                 MECNET
1845                  True   Sports                 MECNET
1846                  True   Sports                 MECNET
1853                 False   Sports                 MECNET
1858                  True   Sports                 MECNET
1859                  True   Sports                 MECNET
1864                  True   Sports                 MECNET
1868                 False   Sports                 MECNET
1869                 False   Sports                 MECNET
1870                 False   Sports                 MECNET
1871                  True   Sports                 MECNET
1872                 False   Sports                 MECNET
1873                  True   Sports
1876                  True   Sports
1877                  True   Sports
1878                  True   Sports                 MECNET
1879                  True   Sports
1880                  True   Sports                 MECNET
1881                  True   Sports                 MECNET
1882                  True   Sports                 MECNET
1895                 False   Sports
1898                  True   Sports                 MECNET
1899                  True   Sports                 MECNET
1900                  True   Sports                 MECNET
1901                  True   Sports
1902                  True   Sports
1916                  True   Sports                 MECNET
1938                  True   Sports                 MECNET
1939                 False   Sports
1945                  True   Sports                 MECNET
1948                  True   Sports                 MECNET
1951                  True   Sports
1955                 False   Sports                 MECNET
1960                  True   Sports
1961                  True   Sports
1962                  True   Sports
1963                  True   Sports
1964                  True   Sports
1965                  True   Sports
1966                 False   Sports
1969                  True   Sports                 MECNET
1970                  True   Sports
1971                  True   Sports                 MECNET
1972                  True   Sports                 MECNET
1986                  True   Sports
1987                  True   Sports
1988                  True   Sports
1989                  True   Sports                 MECNET
1990                  True   Sports                 MECNET
1992                  True   Sports               DIRECNET
1993                  True   Sports               DIRECNET
1994                  True   Sports               DIRECNET
1995                  True   Sports               DIRECNET
1996                  True   Sports               DIRECNET
1997                  True   Sports               DIRECNET
1998                  True   Sports               DIRECNET
1999                  True   Sports               DIRECNET
2000                  True   Sports               DIRECNET
2001                  True   Sports               DIRECNET
2002                  True   Sports               DIRECNET
2003                  True   Sports               DIRECNET
2004                  True   Sports               DIRECNET
2005                  True   Sports               DIRECNET
2006                  True   Sports               DIRECNET
2007                  True   Sports               DIRECNET
2008                  True   Sports               DIRECNET
2009                  True   Sports               DIRECNET
2010                  True   Sports               DIRECNET
2011                  True   Sports               DIRECNET
2012                  True   Sports               DIRECNET
2013                  True   Sports               DIRECNET
2014                  True   Sports               DIRECNET
2015                  True   Sports               DIRECNET
2016                  True   Sports               DIRECNET
2017                  True   Sports               DIRECNET
2018                  True   Sports               DIRECNET
2019                  True   Sports               DIRECNET
2020                  True   Sports               DIRECNET
2021                  True   Sports               DIRECNET
2023                  True   Sports
2024                  True   Sports
2030                  True   Sports
2032                  True   Sports                 MECNET
2037                  True   Sports                 MECNET
2038                  True   Sports                 MECNET
2039                  True   Sports                 MECNET
2043                 False   Sports                 MECNET
2046                  True   Sports                 MECNET
2048                  True   Sports                 MECNET
2050                  True   Sports
2052                  True   Sports                 MECNET
2053                  True   Sports                 MECNET
2054                  True   Sports
2055                  True   Sports                 MECNET
2056                  True   Sports                 MECNET
2057                  True   Sports                 MECNET
2058                  True   Sports                 MECNET
2059                  True   Sports                 MECNET
2060                  True   Sports                 MECNET
2061                  True   Sports                 MECNET
2062                  True   Sports                 MECNET
2071                  True   Sports                 MECNET
2072                 False   Sports                 MECNET
2073                 False   Sports                 MECNET
2074                 False   Sports                 MECNET
2075                 False   Sports                 MECNET
2076                  True   Sports
2077                  True   Sports
2078                  True   Sports
2079                  True   Sports
2080                  True   Sports
2081                  True   Sports
2082                  True   Sports
2083                  True   Sports
2084                  True   Sports
2085                  True   Sports
2086                  True   Sports
2087                  True   Sports
2088                  True   Sports                 MECNET
2089                  True   Sports                 MECNET
2090                  True   Sports                 MECNET
2091                  True   Sports                 MECNET
2092                  True   Sports                 MECNET
2093                  True   Sports                 MECNET
2094                  True   Sports                 MECNET
2095                  True   Sports                 MECNET
2096                  True   Sports                 MECNET
2097                  True   Sports                 MECNET
2098                  True   Sports                 MECNET
2099                  True   Sports                 MECNET
2100                 False   Sports                 MECNET
2101                 False   Sports                 MECNET
2102                 False   Sports                 MECNET
2103                 False   Sports                 MECNET
2104                 False   Sports                 MECNET
2105                 False   Sports                 MECNET
2106                 False   Sports                 MECNET
2107                  True   Sports
2108                  True   Sports
2109                 False   Sports                 MECNET
2110                  True   Sports                 MECNET
2111                 False   Sports                 MECNET
2113                 False   Sports                 MECNET
2114                  True   Sports                 MECNET
2115                 False   Sports                 MECNET
2116                 False   Sports                 MECNET
2117                 False   Sports                 MECNET
2118                 False   Sports                 MECNET
2119                  True   Sports                 MECNET
2122                 False   Sports                 MECNET
2123                 False   Sports                 MECNET
2124                  True   Sports                 MECNET
2125                  True   Sports                 MECNET
2127                 False   Sports                 MECNET
2128                  True   Sports
2129                 False   Sports                 MECNET
2130                 False   Sports                 MECNET
2131                  True   Sports                 MECNET
2133                 False   Sports                 MECNET
2134                 False   Sports                 MECNET
2135                  True   Sports                 MECNET
2136                 False   Sports                 MECNET
2137                  True   Sports                 MECNET

In [2]:
from kalshi.markets import Markets
from kalshi.utils import utc_to_local
markets = Markets()
markets = markets.get_all_markets(all_pages=False, status='open', mve_filter='exclude')
markets_df = pd.DataFrame(markets)
cols = markets_df.columns
for col in cols:
    if 'time' in col:
        markets_df[col] = markets_df[col].apply(utc_to_local)

In [3]:
display(markets_df.sort_values('close_time', ascending=True).head())

,can_close_early,close_time,created_time,custom_strike,early_close_condition,event_ticker,expected_expiration_time,expiration_time,expiration_value,fractional_trading_enabled,last_price_dollars,latest_expiration_time,liquidity_dollars,market_type,no_ask_dollars,no_bid_dollars,no_sub_title,notional_value_dollars,open_interest_fp,open_time,previous_price_dollars,previous_yes_ask_dollars,previous_yes_bid_dollars,price_level_structure,price_ranges,response_price_units,result,rules_primary,rules_secondary,settlement_timer_seconds,status,strike_type,subtitle,tick_size,ticker,title,updated_time,volume_24h_fp,volume_fp,yes_ask_dollars,yes_ask_size_fp,yes_bid_dollars,yes_bid_size_fp,yes_sub_title,floor_strike
99,True,2026-03-22 12:00:00-05:00,2026-03-20 06:01:28.085970-05:00,{'baseball_team': '8c0f942e-918c-48e3-b1c2-6b1...,This market will close and expire after a winn...,KXNCAABBGAME-26MAR201300GETPIT,2026-03-20 17:00:00-05:00,2026-03-22 12:00:00-05:00,,False,0.6400,2026-03-22 12:00:00-05:00,0.0000,binary,0.3600,0.2100,Georgia Tech,1.0000,26.00,2026-03-20 06:06:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Georgia Tech wins the Georgia Tech vs Pitt ...,"Kalshi is not affiliated, associated, authoriz...",1969-12-31 18:05:00-06:00,active,structured,,1,KXNCAABBGAME-26MAR201300GETPIT-GET,Georgia Tech vs Pitt winner?,2026-03-20 06:06:00.714587-05:00,26.00,26.00,0.7900,2392.00,0.6400,400.00,Georgia Tech,NaN
98,True,2026-03-22 12:00:00-05:00,2026-03-20 06:01:28.085970-05:00,{'baseball_team': 'e9406701-070f-4e2a-8971-5fc...,This market will close and expire after a winn...,KXNCAABBGAME-26MAR201300GETPIT,2026-03-20 17:00:00-05:00,2026-03-22 12:00:00-05:00,,False,0.0000,2026-03-22 12:00:00-05:00,0.0000,binary,0.7300,0.1300,Pitt,1.0000,0.00,2026-03-20 06:06:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Pitt wins the Georgia Tech vs Pitt College ...,"Kalshi is not affiliated, associated, authoriz...",1969-12-31 18:05:00-06:00,active,structured,,1,KXNCAABBGAME-26MAR201300GETPIT-PIT,Georgia Tech vs Pitt winner?,2026-03-20 06:06:00.714587-05:00,0.00,0.00,0.8700,3846.00,0.2700,400.00,Pitt,NaN
88,True,2026-03-22 13:00:00-05:00,2026-03-20 07:01:38.659801-05:00,{'baseball_team': 'f32d971e-9dcd-47c6-b062-061...,This market will close and expire after a winn...,KXNCAABBGAME-26MAR201400LIUCBD,2026-03-20 18:00:00-05:00,2026-03-22 13:00:00-05:00,,False,0.0000,2026-03-22 13:00:00-05:00,0.0000,binary,0.9700,0.0300,LIU,1.0000,0.00,2026-03-20 07:06:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If LIU wins the LIU vs Central Connecticut Col...,"Kalshi is not affiliated, associated, authoriz...",1969-12-31 18:05:00-06:00,active,structured,,1,KXNCAABBGAME-26MAR201400LIUCBD-LIU,LIU vs Central Connecticut winner?,2026-03-20 07:06:00.714791-05:00,0.00,0.00,0.9700,102.00,0.0300,50.00,LIU,NaN
87,True,2026-03-22 13:00:00-05:00,2026-03-20 07:01:41.375240-05:00,{'baseball_team': 'f9d17392-7ce8-47bd-a303-f68...,This market will close and expire after a winn...,KXNCAABBGAME-26MAR201400ELONEH,2026-03-20 18:00:00-05:00,2026-03-22 13:00:00-05:00,,False,0.0000,2026-03-22 13:00:00-05:00,0.0000,binary,0.9700,0.0300,Elon,1.0000,0.00,2026-03-20 07:06:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Elon wins the Elon vs Northeastern College ...,"Kalshi is not affiliated, associated, authoriz...",1969-12-31 18:05:00-06:00,active,structured,,1,KXNCAABBGAME-26MAR201400ELONEH-ELO,Elon vs Northeastern winner?,2026-03-20 07:06:00.714791-05:00,0.00,0.00,0.9700,133.00,0.0300,50.00,Elon,NaN
86,True,2026-03-22 13:00:00-05:00,2026-03-20 07:01:41.375240-05:00,{'baseball_team': '785f51f7-8ecc-4759-962a-011...,This market will close and expire after a winn...,KXNCAABBGAME-26MAR201400ELONEH,2026-03-20 18:00:00-05:00,2026-03-22 13:00:00-05:00,,False,0.0000,2026-03-22 13:00:00-05:00,0.0000,binary,0.9700,0.0300,Northeastern,1.0000,0.00,2026-03-20 07:06:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Northeastern wins the Elon vs Northeastern ...,"Kalshi is not affiliated, associated, authoriz...",1969-12-31 18:05:00-06:00,active,structured,,1,KXNCAABBGAME-26MAR201400ELONEH-NEH,Elon vs Northeastern winner?,2026-03-20 07:06:00.714791-05:00,0.00,0.00,0.9700,25.00,0.0300,50.00,Northeastern,NaN

In [4]:
display(markets_df.custom_strike)

0     {'baseball_team': '9c46e0c3-3f42-43da-8e15-8e1...
1     {'baseball_team': '023f446d-8bd9-4888-aff9-2f9...
2     {'baseball_team': 'de14d6e9-999b-41e3-a7ad-a46...
3     {'baseball_team': '68e87bc9-d917-4d05-8efe-b68...
4     {'baseball_team': 'd0ce451e-4cf2-424b-a999-4d3...
5     {'baseball_team': '1659c019-374a-4358-bca8-d9b...
6     {'baseball_team': 'fb1d84e9-a8ee-4fff-a0ae-e9a...
7     {'baseball_team': '04646928-739a-4d3f-9828-7ac...
8     {'baseball_team': '95efe31d-0a3d-4fcd-bc79-a89...
9     {'baseball_team': 'a7a900a3-b7b9-43fc-802a-581...
10    {'baseball_team': 'cdd83458-e62a-4968-b854-811...
11    {'baseball_team': '71944105-6492-4e3b-983a-b06...
12    {'baseball_team': 'c8a5c419-97fe-4b92-92bc-444...
13    {'baseball_team': '33b8b75a-b7b2-4329-91a6-8dd...
14    {'baseball_team': '561af440-84b2-49b9-b0f2-68a...
15    {'baseball_team': '238eba43-3fcf-4ec3-81ce-9da...
16    {'baseball_team': '4e995568-dc4e-4198-960c-850...
17    {'baseball_team': 'b8277a0a-dc40-40cf-a9a9-b4f...
18    {'baseball_team': 'fc6bf043-5934-4944-b495-52e...
19    {'baseball_team': '7836bbca-ee0f-4ab2-885b-469...
20    {'baseball_team': '0b9e9b96-c636-47db-9786-82a...
21    {'baseball_team': '211dbd25-b555-46c8-b81d-97c...
22    {'baseball_team': '06003da0-0816-4ea1-9509-35a...
23    {'baseball_team': '336e58f8-4fe5-4afa-b485-12f...
24    {'baseball_team': 'f865440b-b91e-4c71-8b64-537...
25    {'baseball_team': '47623f74-a1ba-478b-ba37-003...
26    {'baseball_team': '22d6ca25-d012-4415-a54b-2a6...
27    {'baseball_team': 'badfbea5-61f0-4834-b6bf-463...
28    {'baseball_team': '2f78c49b-de66-499f-9bf3-e77...
29    {'baseball_team': '4786752d-20cf-4804-9376-530...
30    {'baseball_team': '90d82c75-03f9-413f-a42c-787...
31    {'baseball_team': 'a03c1523-e0bc-43eb-a24d-02d...
32    {'baseball_team': 'aef495ae-f265-4175-be47-0f3...
33    {'baseball_team': '575e9ac7-010b-4188-8ff0-00e...
34    {'baseball_team': '4adf3bd6-45a1-40d9-971d-108...
35    {'baseball_team': '475d908c-7ec9-4328-af6a-a42...
36    {'baseball_team': 'a06bfd14-bff0-4096-b1bb-e6b...
37    {'baseball_team': 'af2e70d9-7b71-4e6c-a44d-d16...
38    {'baseball_team': 'b866fdb3-2e09-4a24-b6f4-492...
39    {'baseball_team': '2530a3b8-1c9a-489e-855a-068...
40    {'baseball_team': '5d862541-0d6c-47ed-a4fb-5a7...
41    {'baseball_team': 'a8070f03-c07f-40a5-a965-d19...
42    {'baseball_team': '32eb1534-ae9d-4fa1-9bb5-263...
43    {'baseball_team': 'acffcd3c-d0c0-44e0-a29f-1be...
44    {'baseball_team': '3a72d659-7271-4493-b05f-c51...
45    {'baseball_team': '9e418d62-e2ce-420b-baad-5cc...
46    {'baseball_team': '469eb633-0736-42a8-902d-b17...
47    {'baseball_team': '63554361-9697-4335-bd7b-17b...
48    {'baseball_team': '1d143572-a7ae-4367-bfeb-85b...
49    {'baseball_team': 'e370dd9d-4ada-4016-8b76-423...
50    {'baseball_team': 'e19f1517-31ba-4a72-aa3b-4d8...
51    {'baseball_team': '088218c1-1afa-4dd9-8a4d-b5c...
52    {'baseball_team': 'f12a309d-3b7a-4b07-b91f-1ed...
53    {'baseball_team': '0263446b-8665-47d9-9523-b8f...
54    {'baseball_team': '1e023dca-27b1-42cd-99d3-187...
55    {'baseball_team': '69361e77-cc49-4cd5-9ecc-a38...
56    {'basketball_team': 'ab9e2e9a-3243-41b6-a291-9...
57    {'basketball_team': '7cc1eb26-46ee-44b7-94ad-2...
58    {'basketball_team': '2229b01e-68eb-46ad-adf4-7...
59    {'basketball_team': 'ba2cb6be-9827-46a8-8e6f-d...
60                                                  NaN
61                                                  NaN
62                                                  NaN
63                                                  NaN
64                                                  NaN
65                                                  NaN
66                                                  NaN
67                                                  NaN
68                                                  NaN
69                                                  NaN
70                                                  NaN
71    {'basketball_team': '00c3e69d-d9b9-4ac3-bf79-1...
72    {'basketball_team': '00c3e69d-d9b9-4ac3-bf79-1...
73    {'basketball_team': '00c3e69d-d9b9-4ac3-bf79-1...
74    {'basketball_team': '00c3e69d-d9b9-4ac3-bf79-1...
75    {'basketball_team': '00c3e69d-d9b9-4ac3-bf79-1...
76    {'basketball_team': '2ef4d31c-0b46-4f43-a403-f...
77    {'basketball_team': '2ef4d31c-0b46-4f43-a403-f...
78    {'basketball_team': '2ef4d31c-0b46-4f43-a403-f...
79    {'basketball_team': '2ef4d31c-0b46-4f43-a403-f...
80    {'basketball_team': '2ef4d31c-0b46-4f43-a403-f...
81    {'basketball_team': '2ef4d31c-0b46-4f43-a403-f...
82    {'baseball_team': 'f02968e7-0da3-4cdc-b711-06c...
83    {'baseball_team': 'e00bf4b7-35a3-483b-8d3d-49d...
84    {'baseball_team': 'fb298280-e901-4dcb-a8bd-5a4...
85    {'baseball_team': '2d7a8e48-80b9-4c65-9d67-558...
86    {'baseball_team': '785f51f7-8ecc-4759-962a-011...
87    {'baseball_team': 'f9d17392-7ce8-47bd-a303-f68...
88    {'baseball_team': 'f32d971e-9dcd-47c6-b062-061...
89    {'baseball_team': '0a92f5af-7cfd-496a-9af7-0df...
90    {'basketball_team': '111193d4-9b1f-4bd8-ab8b-9...
91    {'basketball_team': '00c3e69d-d9b9-4ac3-bf79-1...
92    {'basketball_team': '2ef4d31c-0b46-4f43-a403-f...
93    {'basketball_team': '111193d4-9b1f-4bd8-ab8b-9...
94    {'basketball_team': '00c3e69d-d9b9-4ac3-bf79-1...
95    {'basketball_team': '2ef4d31c-0b46-4f43-a403-f...
96    {'hockey_team': 'cb3e7b15-911b-4a68-ac10-bc75b...
97    {'hockey_team': '31806998-381c-490a-b0e5-5e9b8...
98    {'baseball_team': 'e9406701-070f-4e2a-8971-5fc...
99    {'baseball_team': '8c0f942e-918c-48e3-b1c2-6b1...
Name: custom_strike, dtype: object

In [ ]:
display(markets_df.describe().transpose())

In [ ]:
display(markets_df.describe().transpose())