In [1]:
import pandas as pd

In [2]:
from kalshi.events import Events

events = Events()
events = events.get_events(all_pages=False)
events_df = pd.DataFrame(events)
display(events_df.head())

,available_on_brokers,category,collateral_return_type,event_ticker,last_updated_ts,mutually_exclusive,series_ticker,strike_period,sub_title,title,product_metadata
0,True,World,,KXELONMARS-99,2026-02-26T08:50:31.901806Z,False,KXELONMARS,,Before 2099,Will Elon Musk visit Mars in his lifetime?,NaN
1,True,World,MECNET,KXNEWPOPE-70,2026-02-26T08:50:31.901806Z,True,KXNEWPOPE,,Before 2070,Who will the next Pope be?,NaN
2,True,Climate and Weather,,KXWARMING-50,2026-02-26T08:50:31.901806Z,False,KXWARMING,,Before 2050,Will the world pass 2 degrees Celsius over pre...,NaN
3,True,Science and Technology,,KXMARSVRAIL-50,2026-02-26T08:50:31.901806Z,False,KXMARSVRAIL,,Before 2050,Will a human land on Mars before California st...,NaN
4,True,Climate and Weather,,KXERUPTSUPER-0,2026-02-26T08:50:31.901806Z,False,KXERUPTSUPER,,a supervolcano,Will a supervolcano erupt before 2050?,NaN

In [5]:
display(events_df.columns)

Index(['available_on_brokers', 'category', 'collateral_return_type',
       'event_ticker', 'last_updated_ts', 'mutually_exclusive',
       'series_ticker', 'strike_period', 'sub_title', 'title',
       'product_metadata'],
      dtype='str')

In [7]:
display(events_df.describe().transpose())

,count,unique,top,freq
available_on_brokers,100,2,True,61
category,100,12,Entertainment,25
collateral_return_type,100,3,,76
event_ticker,100,100,KXELONMARS-99,1
last_updated_ts,100,6,2026-02-26T08:50:31.901806Z,95
mutually_exclusive,100,2,False,78
series_ticker,100,92,KXPERFORMROLE007,6
strike_period,100,1,,100
sub_title,100,46,Before 2030,28
title,100,97,Who will the next Pope be?,3
product_metadata,4,2,{'competition': 'Pro Basketball (M)'},3

In [8]:
display(events_df['category'].value_counts())

category
Entertainment             25
Politics                  22
Climate and Weather        9
Science and Technology     8
Economics                  7
World                      6
Sports                     6
Companies                  5
Financials                 4
Social                     3
Elections                  3
Health                     2
Name: count, dtype: int64